# folder settings
source: .
destination: ./_site

# site settings
permalink: /:categories/:title
markdown: rdiscount

# site url
url: saitowu.github.com

# Focus domain name to site.url, used for CloudFront production only
# prod: true
prod: true

# used by images inserted in posts
file: http://i.imgur.com/

# used by css url in default.html and index.xml
css-path: /css

# custom vars, most of them are used by index.xml
name: Saito
full-name: Saito Wu
email: saitowu@gmail.com
slogan: worstest coder ever.
twitter: SaitoWu

# fire up a localhost and auto generate when files change
auto: true
server: ture
server_port: 4321

# exclude files for generated site
exclude:
- README.md
- LICENSE
- Rakefile
- nite.tmproj

